version: "2"
services:
  # Postgres DB Container
  postgres:
    image: "postgres:18"
    ports:
      # <Port exposed> : < PGSQL Port running inside container>
      - "5432:5432"
    volumes:
      - ./docker-data/pg:/var/lib/postgresql/18/docker
      - ./docker/provision/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "boilerplate_development"
      POSTGRES_USER: "bp_user"
      POSTGRES_PASSWORD: "bp_password"
  # S3 Localstack for local AWS services, you may add other AWS services, see https://github.com/localstack/localstack
  # localstack-s3:
  #   image: localstack/localstack
  #   volumes:
  #     - ./docker-data/localstack:/tmp/localstack
  #   ports:
  #     - 5000:5000
  #     - 8080:8080
  #   environment:
  #     - SERVICES=s3:5000,web:8080
  #     - DEFAULT_REGION=us-west-2
  #     - DATA_DIR=/tmp/localstack/data
  # Redis Cache
  # redis:
  #   image: "redis:5-alpine"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./docker-data/redis:/data
